version: "3.5"
services:
  webapp:
    build:
      context: ./lp
    ports:
    - "5003:5003"
    environment:
      DPORT: 5003
  weblapp:
    build:
      context: ./ex
    ports:
    - "5005:5005"
    environment:
      DPORT: 5005
