from SCons.Environment import Environment

client = Environment(CC = '/usr/bin/clang',
                     CXX = '/usr/bin/clang++', 
                     CXXFLAGS = ['-std=c++17', '-fPIE',
                                 '-Iinclude'],
                     LINKFLAGS = ['-Linclude',
                                  '-Ltls/.libs',
                                  '-Lcrypto/.libs',
                                  '-ltls', '-lcrypto'])

client.Program(target='tclient', source=['source/tclient.cpp', 
                                        'source/http.cpp',
                                        'tls/.libs/libtls.a',
                                        'crypto/.libs/libcrypto.a'])
